### ISSUE TITLE
Runnning comparem issue

### ISSUE THREAD

**Issue by sbridel** [dparks1134/CompareM#10]
```
comparem aai_wf MAGE_data outputdir
  File "/usr/local/bin/comparem", line 70
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'
```

I dont know what's going on. I'm using python 3.6

**Comment by dparks1134** [comment]
At this time, CompareM requires Python 2.x.

**Comment by sbridel** [comment]
```
python2.7 /usr/local/bin/comparem
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 35, in <module>
    from comparem.main import OptionsParser

```

What's going on? Can you help me please?

**Comment by dparks1134** [comment]
Are you using Python 2.x now? How did you install CompareM? Using pip?

**Comment by sbridel** [comment]
As you can see in the commande i launched with python2.7 because i have both python2.7 and python3.X

In addition, i don't underwent why there is this sentence in README:  "The genomic nucleotide sequences of genomes must be in FASTA format."

comparem perfoms an AAI by translating DNA sequences into RNA sequences, run global alivgnement and then compute identity? I thought that AAI must perform local alignement between homolog genes.
If you put genomic nucleotide sequence of genome you will not have genes information.

Does it require a genome multifasta file with only DNA genes sequences ?

**Comment by dparks1134** [comment]
By default, CompareM will call genes using Prodigal. However, you can specify that you have already called genes if this is the case. 

I'm not sure why CompareM is not working on your system. My best guess is that it was install into Python 3.x, but you are now trying to run it in Python 2.x. Did you install CompareM with pip?

**Comment by sbridel** [comment]
Yes but maybe pip has installed it in python3.X 
I tried in another computer with python 3.X and it works
