### ISSUE TITLE
Can you please specify format file input

### ISSUE THREAD

**Issue by sbridel** [dparks1134/CompareM#11]
My question is:
What's the file format if I want to use my annotated genomes ?

1- CDS
```
>gene_1
ATGGGCATACGATAGAGACT..
>gene_2
ATGCCCGATACAGATCATGAT..
```
or 2- Proteins?
```
>gene_1
MKLVIS...
>gene_2
MSADEPHR..
```
Thanks

**Comment by dparks1134** [comment]
By default, CompareM will call genes for you using Prodigal. If you want to provide protein use the <code>--proteins</code> flag. Protein files must be in format 2 (i.e., amino acid space).

**Comment by sbridel** [comment]
```
time(comparem aai_wf --proteins Test_prot/merged_prot.faa -c 8 TEST/)
[2017-04-03 10:50:56] INFO: CompareM v0.0.21
[2017-04-03 10:50:56] INFO: comparem aai_wf --proteins Test_prot/merged_prot.faa -c 8 TEST/
[2017-04-03 10:50:56] WARNING: Changing file extension from 'fna' to 'faa' since 'proteins' flag was given.
[2017-04-03 10:50:56] ERROR: Specified input file does not exist: >WP_002988156.1 MULTISPECIES: acyl carrier protein [Flavobacteriaceae]

  Controlled exit resulting from an unrecoverable error or warning.

real	0m0.494s
user	0m0.417s
sys	0m0.076s

```
I dpon't know what's going on

**Comment by dparks1134** [comment]
CheckM expects either a directory of files (i.e. all *.faa files your wish to process a single directory) or a file indicating the path to files to process (one file per line). Right now, it is reading your "merged_prot.faa" file to determine where each of your protein files is.

**Comment by sbridel** [comment]
Thanks
