### ISSUE TITLE
Orthologs not found

### ISSUE THREAD

**Issue by annalisa14** [dparks1134/CompareM#14]
Hello! I used this tool to calculate AAI between my genome files belonging to the same genus. The results obtained are not as expected since the programme cannot find any orthologs. 
For instance: 
GCA_000025705.1_ASM2570v1_protein	2980 GCA_001830495.1_ASM183049v1_protein	698	0	0.00	0.00	0.00
GCA_001830535.1_ASM183053v1_protein 694	GCA_001830495.1_ASM183049v1_protein	698	0	0.00	0.00	0.00

Differently, using another tool, AAI calculator (http://enve-omics.ce.gatech.edu/aai/) I could get the following AAI values for the same genomes:

Between GCA_000025705.1_ASM2570v1_protein.faa and GCA_001830485.1_ASM183048v1_protein.faa | 

One-way AAI 1: 46.90% (SD: 23.42%), from 2971 proteins.
One-way AAI 2: 74.33% (SD: 21.58%), from 930 proteins.
Two-way AAI: 78.90% (SD: 17.55%), from 832 proteins.

Between GCA_001830495.1_ASM183049v1_protein.faa and GCA_001830535.1_ASM183053v1_protein.faa 

One-way AAI 1: 54.75% (SD: 28.02%), from 697 proteins.
One-way AAI 2: 55.46% (SD: 28.24%), from 693 proteins.
Two-way AAI: 72.97% (SD: 27.37%), from 357 proteins.

Do you know what might be the problem?

**Comment by dparks1134** [comment]
Does CompareM run without error? Some people have been having the same issue which we narrowed down to between the 'sort' command on different Linux flavours. I haven't had a chance to address this issue yet.

**Comment by annalisa14** [comment]
Yes, CompareM runs without any error. I will try to find out how to solve this issue.
Thanks for your reply.

**Comment by c1imbe2** [comment]
Same problem here. Running macOS High Sierra 10.13.3. All updated dependencies installed. comparem shows no errors, all files appear to be as they should except for aai_summary.tsv, which contains information in the first 4 columns but contains no orthologs or AAI information. I also tried the remedy listed here (https://github.com/dparks1134/CompareM/issues/16) to modify the sed syntax and use 'gsort' in place of 'sort' within simliarity_search.py, in to no avail. Didn't find anything else that jumps out at me. Has anyone had any luck fixing this issue?

**Comment by nohayoussef** [comment]
I ran into the same issue running it on linux server. Did anyone figure this out yet?

**Comment by 473021677** [comment]
I have used CompareM  to calculate AAI between my genome files but the program couldn't find any orthologs. CompareM runs without any error. Could somesone fix this issue?

**Comment by dparks1134** [comment]
There is a known issue related to different implementations of 'sort' in different Linux flavours. Unfortunately, there are no immediate plans to address this issue. The AAI calculator from the Kostas Lab is an alternative solution: http://enve-omics.ce.gatech.edu/aai/.

**Comment by vinisalazar** [comment]
I'd just like to add that I've had this same problem when calculating aai_wf between 165 genomes. However, when I did a test run on only 3 genomes from the same dataset, the output came out right.

**Comment by vinisalazar** [comment]
Hi,

I could fix the problem by rerunning `aai_wf` on the `genes` folder of a previous `aai_wf` output. Basically:

`comparem aai_wf genomic_fna/ comparem_aai-c 32` -- identified no orthologs.

`comparem aai_wf comparem_aai/genes/ second_try -c 32` -- this worked properly.

Any thoughts?

**Comment by dparks1134** [comment]
Closing old issues as CompareM is being migrated to Python 3.
