### ISSUE TITLE
Can I customize the order of the target genome files in the aai_wf result? Or can you get the full matrix of pairwise AAI distance?

### ISSUE THREAD

**Issue by zhssakura** [dparks1134/CompareM#17]
Hi，
Can I customize the order of the target genome files in the aai_wf result? Or can I get the full matrix of pairwise AAI distance? Thanks~

**Comment by dparks1134** [comment]
Sorry for the late response. I'm not sure I follow. The aai_wf command does do all pairwise comparisons.

**Comment by johanneswerner** [comment]
Can you provide a table or matrix-like output for all-against-all?

I have a large list of bacteria, and I am not sure how to parse the output format into a table-like structure (and it would be helpful to have the organisms in their diagonal that match with 100% against themselves).

**Comment by dparks1134** [comment]
Closing all old issues before migrating to Python 3.
