### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Felixseetoo** [dparks1134/CompareM#22]
Hi, 

I am trying to install compareM using python 2.7.15. However, I get an error as below: 

File "/tmp/pip-install-hBSQZJ/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hBSQZJ/tornado/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

May I know what can I do?

Thank you.

**Comment by dparks1134** [comment]
CompareM does not use Tornado. I'm unclear why this is being installed. Perhaps one of the dependencies used by CompareM used Tornado? I'd suggest trying to install the CompareM Python dependencies independently to determine which one is causing the issue.

**Comment by Felixseetoo** [comment]
Ok, thanks. I reinstall the python and the problem is solved.
