### ISSUE TITLE
lgt analysis

### ISSUE THREAD

**Issue by naianegri** [dparks1134/CompareM#24]
Hey guys,

I'm trying to interpret the relevant data from the lgt_di and lgt_codon analysis with comparem

Where can I find the threshold value for Manhattan distance? Or for Deviations from mean? How can I say that the gene is obtained from lateral transfer?

Thanks.

**Comment by dparks1134** [comment]
CompareM implements the test in Hooper and Berg:
https://www.ncbi.nlm.nih.gov/pubmed/11847562

I'm not an expert in this test so can't provide direct advice on interpreting the results.

The CompareM user manual has more details about running this command:
https://github.com/dparks1134/CompareM/blob/master/users_guide.pdf
