### ISSUE TITLE
missing comparison in aai output file

### ISSUE THREAD

**Issue by efr3m** [dparks1134/CompareM#25]
I run CompareM v0.0.23 for aai calculation between a set of 46 genomes.
I would expect that each genome is compared with the other 45 but this is not the case as sometimes I have only 42 comparisons, sometimes I have just 27 and so on.

During the run I did not have any issue, and in genera the results are consistent with my other anlyses.
Any idea where the issue might be?
Thanks very much for your help.
Best regards
Stefano

**Comment by dparks1134** [comment]
I haven't seen this issue before. What is the exact command you are running? What is the output of CompareM?

**Comment by efr3m** [comment]
Hi @dparks1134 Sorry for the late reply.
Considering your surprise I re-run everything and this time I got the right number of comparison: each genome was compared to any other genome.
I have no idea what happened before. Could be that DIAMOND crashed?

Thanks again!
