### ISSUE TITLE
install issue : Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Diamonds95** [dparks1134/CompareM#26]
Hello! When I install comparem, I found the trouble like:
![image](https://user-images.githubusercontent.com/41280750/56265348-dcec5d80-611b-11e9-9f8f-6a2d8e977e38.png)
so I use bioconda create a python2 virtual environment ,but when I try to install, it still failed,like this:
![1](https://user-images.githubusercontent.com/41280750/56265610-951a0600-611c-11e9-9ebb-28a04fc348f7.jpg)
Hope your reply! Thanks a lot!

**Comment by dparks1134** [comment]
CompareM must be run with Python 2.x. The error message indicates you are running it with Python 3.x.

**Comment by DaoxinDai** [comment]
Thanks！but when i try to find the version of Python,  it showed: Python 2.7.15! It's really confused me!

**Comment by dparks1134** [comment]
Closing old issues before migrating to Python 3.
