### ISSUE TITLE
Could I calculate AAI of eukaryotes by CompareM?

### ISSUE THREAD

**Issue by DustinChen1986** [dparks1134/CompareM#33]
Could I calculate AAI of eukaryotes by CompareM, or I can combine Orthofinder or OrthoMCL with CompareM to calculate AAI between eukaryotic genomes?

**Comment by dparks1134** [comment]
CompareM is designed with bacterial and archaeal genomes in mind. In particular, it uses Prodigal to call genes which assumes the input genome in bacterial or archaeal. However, if you provide the called genes it should work for Euks.

**Comment by DustinChen1986** [comment]
Thank you for your reply.
