### ISSUE TITLE
biolib>=0.0.8

### ISSUE THREAD

**Issue by jfkell05** [dparks1134/CompareM#4]
Installing through pip, does not pull the correct biolib package.  Using pip to install biolib, also does not install package above 0.0.7.
I am not great at installing python packages - so I am having trouble with the issue.

>$ sudo pip install comparem
Downloading/unpacking comparem
  Downloading comparem-0.0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/comparem/setup.py) egg_info for package comparem
 
>Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from comparem)
Downloading/unpacking biolib>=0.0.8 (from comparem)
  Could not find a version that satisfies the requirement biolib>=0.0.8 (from comparem) (from versions: 0.0.7)
Cleaning up...
No distributions matching the version for biolib>=0.0.8 (from comparem)
Storing debug log for failure in /home/user/.pip/pip.log

pip.log:

> ------------------------------------------------------------
/usr/bin/pip run on Wed Apr 13 08:36:07 2016
Downloading/unpacking comparem
  Getting page https://pypi.python.org/simple/comparem/
  URLs to search for versions for comparem:
  * https://pypi.python.org/simple/comparem/
  Analyzing links from page https://pypi.python.org/simple/comparem/
    Found link https://pypi.python.org/packages/source/c/comparem/comparem-0.0.3.tar.gz#md5=7ea2189727659eae286204ff2d290445 (from https://pypi.python.org/simple/comparem/), version: 0.0.3
    Found link https://pypi.python.org/packages/source/c/comparem/comparem-0.0.5.tar.gz#md5=03b0cc922786b3f3f210383df0306741 (from https://pypi.python.org/simple/comparem/), version: 0.0.5
  Using version 0.0.5 (newest of versions: 0.0.5, 0.0.3)
  Downloading comparem-0.0.5.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/c/comparem/comparem-0.0.5.tar.gz#md5=03b0cc922786b3f3f210383df0306741 (from https://pypi.python.org/simple/comparem/)
  Running setup.py (path:/tmp/pip_build_root/comparem/setup.py) egg_info for package comparem
    running egg_info
    creating pip-egg-info/comparem.egg-info
    writing requirements to pip-egg-info/comparem.egg-info/requires.txt
    writing pip-egg-info/comparem.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/comparem.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/comparem.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/comparem.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
>    reading manifest file 'pip-egg-info/comparem.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/comparem.egg-info/SOURCES.txt'
>  Source in /tmp/pip_build_root/comparem has version 0.0.5, which satisfies requirement comparem
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from comparem)
Downloading/unpacking biolib>=0.0.8 (from comparem)
  Getting page https://pypi.python.org/simple/biolib/
  URLs to search for versions for biolib>=0.0.8 (from comparem):
>  * https://pypi.python.org/simple/biolib/
  Analyzing links from page https://pypi.python.org/simple/biolib/
    Found link https://pypi.python.org/packages/source/b/biolib/biolib-0.0.7.tar.gz#md5=92cb61495d3358ad4d2d04501a7375bb (from https://pypi.python.org/simple/biolib/), version: 0.0.7
  Ignoring link https://pypi.python.org/packages/source/b/biolib/biolib-0.0.7.tar.gz#md5=92cb61495d3358ad4d2d04501a7375bb (from https://pypi.python.org/simple/biolib/), version 0.0.7 doesn't match >=0.0.8
  Could not find a version that satisfies the requirement biolib>=0.0.8 (from comparem) (from versions: 0.0.7)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for biolib>=0.0.8 (from comparem)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for biolib>=0.0.8 (from comparem)

**Comment by dparks1134** [comment]
Thank you for bringing this to my attention, but neither CompareM or biolib are currently ready for general public.

**Comment by jfkell05** [comment]
Oh gotcha - I saw it used in a publication.   That is how I found out about it.  I will continue to check back.  
Thanks for the reply.

John
