### ISSUE TITLE
can't find orthologs between genomes

### ISSUE THREAD

**Issue by ceya** [dparks1134/CompareM#6]
Hello,

I'm using the default setting of comparem aai_wf to calculate aai between my faa genome files and the program cannot find any orthologs. but with the AAI calculator by Kostas lab the score is 99. Does anyone know what might be the problem?

Thank you!
Brooke

**Comment by dparks1134** [comment]
Hello Brooke,

CompareM is still in active development, but I am very surprised to hear this result. Do you mind sending my your genome files and the exact command you are running so I can investigate?

Cheers,
Donovan (donovan.parks [at] gmail.com)

**Comment by ceya** [comment]
Hello Donovan,

Of course, attached are two of my faa files.
I used default setting comparem aai_wf test aai_output (test being my
directory containing the faa files). I also tried adjusting the e-value and
identity cutoff but it didn't help much. I'd really appreciate if you could
have a look and help me identify what might be the issue.

Thank you very much!
Brooke

**Comment by dparks1134** [comment]
Hello Brooke,

I don't see any attached files. Any chance you forgot to attach them? :)

Cheers,
Donovan

**Comment by ceya** [comment]
Hi Donovan,

Can you see them now? I attached four faa files this time.

Regards,
Brooke

**Comment by dparks1134** [comment]
Hello Brooke,

GitHub is very strict on what files can be attached. Can you just email them to me directly at donovan.parks [at] gmail.com.

Thanks,
Donovan

**Comment by dparks1134** [comment]
Hello Brooke,

CompareM processes your genomes fine on my end. I am running the program as follows:
`comparem aai_wf test aai_output --file_ext faa --proteins --cpus 40`

The `file_ext` flag indicates that *.faa files should be processed and the `proteins` flag indicates the FASTA files already contain proteins so gene calling is not necessary. The results indicate that all these genomes are nearly identical (AAI >= 99.98%).

Can you verify that you have the latest version of CompareM (v0.0.16) and DIAMOND >= v0.8.10?

Cheers,
Donovan

**Comment by ceya** [comment]
Hi Donovan,

I've compareM 0.0.16 and diamond v0.8.10.72. I ran the same command except
for the --cpu setting and still have 0 orthologs.

Could it be that the program wasn't installed correctly? I send the whole
aai_output folder to your gmail account. Could you take a look at the files?

Thank you very much!
Brooke

**Comment by dparks1134** [comment]
Hello Brooke,

I think it may have to do with different flavours of Linux. What OS are you using?

Cheers,
Donovan

**Comment by dparks1134** [comment]
Can you also try running CompareM on just the 4 genome you sent me and then sending me the output directory for this? This way I can directly compare my output to your to see where they differ.

**Comment by ceya** [comment]
I'm using a terminal with 64-bit Linux CentOS

**Comment by dparks1134** [comment]
Hello Brooke,

Thank you for helping with the debugging. It does appear to be a Linux flavour issue. Specifically, it has to do with the `sort` command of the OS. CompareM uses sort to index the resulting DIAMOND hits file and I can see that on your machine the file is not actually sorted. Can you check which sort you have on your path (i.e., run `which sort` and let me know what it returns). I'm digging around the net to see if this is a CentOS issue, but I suspect you may just have a different `sort` program on your path other than the standard Unix program.

Thanks
Donovan

**Comment by ceya** [comment]
Hi Donovan,

Here's the output:
[brooke@tatanka comparem]$ which sort
/bin/sort

**Comment by dparks1134** [comment]
Hey,

Seem like this may be a bug with the CentOS implementation of sort:
https://bugs.centos.org/view.php?id=9289

Perhaps you need to update to coreutils-8.22-13.el7.

Cheers,
Donovan

**Comment by ceya** [comment]
Thanks Donovan! I'll contact the admins and let them know.

Regards,
Brooke

**Comment by frederic-foucault** [comment]
Hello
Same results here (no Orthologs found) in OSX 10.11.6
every required binaries were installed or compiled(Diamond)

> which sort
> sort is /usr/bin/sort

**Comment by juliambrosman** [comment]
Incase this is useful for future strugglers, installing comparem into a conda env with bioconda coreutils overcame this issue for me.

```
conda create -n comparem python=2.7 scipy  
conda install --name comparem -c bioconda coreutils  
source activate comparem  
pip install comparem  
```
