### ISSUE TITLE
No pairwise aai statistics come out.

### ISSUE THREAD

**Issue by minsookim1983** [dparks1134/CompareM#9]
Hello,

I did aai_wf workflow of comparem with default settings to calculate aai between assembled contigs, and no orthologs come out in output dir. I checked all the steps, and I found that there was something wrong in similarity step. Specifically, the file named "hits_sorted.tsv" is empty.

What I put it in first in console,
$ comparem aai_wf input_dir/ aai_output/ -x fa --blastp -c 10
; but I did not get anything and no data was observed in "hits_sorted.tsv". 

Next I did similarity only, 
$ comparem similarity aai_output/genes/ aai_output/genes/ similarity_output/ -x faa --blastp -c 10
; but I did not get anything either. So, I tried it again with the values of --per_identity (-p 0) and --per_aln_len (-a 0), but I did not get anything. 

No error messages were shown when doing comparem. I tested it again with NCBI bacterial genomes; it does not work either.

My system is Ubuntu 14.04 x64. Typing with "which sort", I got "/usr/bin/sort". Do you know what might be the problem?

Thank you for your help!
Min-Soo

**Comment by dparks1134** [comment]
Hello Min-Soo,

Did you resolve this issue? 

Cheers,
Donovan

**Comment by minsookim1983** [comment]
Thank you for your answer.
Not yet. I have no idea of how to solve this issue.

Min-Soo

**Comment by minsookim1983** [comment]
Does it look like that there is a problem in my system? Do my output files
support you to figure out what the problem is?
I am looking for aai calculator. My data is large and numerous, so I think
your CompareM is the only tool for me.
I will wait for your response.

Thank you for your kind.
Min-Soo

**Comment by dparks1134** [comment]
Hello Min-Soo,

Can you make sure you have the latest version of both CompareM (v0.0.21) and biolib (v0.0.34) on your system? If the problem still persists, can you narrow the issue down to a pair on input files and send these to me at donovan.parks [at] gmail.com along with the exact command you ran so I can debug the issue.

Regards,
Donovan

**Comment by minsookim1983** [comment]
Thank you for your answer. I check the version of both CompareM and biolib
on my system, and I found that 'sudo pip install' and the version of biolib
(v0.0.34) were in trouble. Now, I confirmed that it works well. I
appreciate your consideration.

Min-Soo

**Comment by dparks1134** [comment]
Excellent. Glad to hear it.
